### ISSUE TITLE
org-msg-edit-mode not set when replying to text emails (mu4e)

### ISSUE THREAD

**Issue by guibor** [jeremy-compostella/org-msg#89] opened 2021-03-29 17:16 UTC
In `org-msg-post-setup` we call `org-msg-edit-mode` only if the message is either new or the field body-html exists in `mu4e-compose-parent-message`.

Although we may want to default to text reply when the original email is text (and this is now possible using `org-msg-alternatives`) behavior should be consistent and we should still be able to reply using org-msg (and all the great functionality that comes with it!).

**Comment by jeremy-compostella** [comment] 2021-04-19 23:12
Hi @guibor,

I made an experimental patch which implement this feature request. Could you give a try?

Regards,
Jeremy

**Comment by morganwillcock** [comment] 2021-04-23 21:17
The export process through Org is damaging to a [signature delimiter](https://tools.ietf.org/html/draft-ietf-usefor-useage-01#section-3.1.2.1), which will likely cause a problem when the recipient of the message goes to reply.

i.e. `-- \n` is being stripped to `--\n`

The problem is visible with `org-msg-preview`.

**Comment by jeremy-compostella** [comment] 2021-04-27 02:17
Good catch! The additional 2f29f7a patch should address this. Let me know what you think.

**Comment by morganwillcock** [comment] 2021-04-27 11:48
On Emacs 27 `flet` doesn't seem to be defined.
 
```
let: Symbol’s function definition is void: flet
```

**Comment by jeremy-compostella** [comment] 2021-04-27 17:45
Indeed, this is an obsolete macro. I re-wrote this using the `cl-letf` macro. Could you verify that the `experimental` branch work for you ?

**Comment by morganwillcock** [comment] 2021-04-28 19:05
It has fixed stripping the whitespace from the end of the line.

When testing further there is also an issue that the signature may be indented if the Org markup has opened a block (e.g. a heading was defined). This isn't immediately obvious when composing/sending because the signature that is inserted automatically is left-aligned. This will also cause an issue with matching the signature as it is common to use the regex pattern "^-- " which will no longer match because of leading whitespace of the indent (see `message-signature-separator`)

**Comment by jeremy-compostella** [comment] 2021-04-28 20:45
The latest version should take care of this.

**Comment by morganwillcock** [comment] 2021-04-29 18:26
Thanks, this version does fix it.

**Comment by jeremy-compostella** [comment] 2021-04-29 20:34
alright, then let's close this ticket.

**Closed by jeremy-compostella** 2021-04-29 20:34 UTC

**Comment by guibor** [comment] 2021-04-29 22:10
Thanks, I actually just had a chance to check this out today and it works great!
